import { setupApp } from "./../../../src/setup-app";
import request from "supertest";
import express from "express";
import { HttpStatus } from "../../../src/core/types";
import { BlogInputDto } from "../../../src/blogs/types/blogs-types";
import { generateBasicAuthToken } from "../../utils/posts/generate-admin-auth-token";
import { getBlogDto } from "../../utils/blogs/get-blog-dto";
import { clearDb } from "../../utils/posts/clear-db";
import { createBlog } from "../../utils/blogs/create-blog";
import { BLOGS_PATH } from "../../../src/core/paths";
import { getBlogById } from "../../utils/blogs/get-blog-by-id";
import { runDB } from "../../../src/db/mongo.db";